### ISSUE TITLE
Fails to run npm install

### ISSUE THREAD

**Issue by slashwhatever** [rwieruch/node-babel-server#9]
As per title.

Run `npm install` after cloning repo.

Output:
```

 ~/xdev/minimal-node-application   master  npm install

> fsevents@1.2.4 install /Users/james/xdev/minimal-node-application/node_modules/fsevents
> node install

node-pre-gyp WARN Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.4/fse-v1.2.4-node-v72-darwin-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.4 and node@12.16.1 (node-v72 ABI, unknown) (falling back to source compile with node-gyp)
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
In file included from ../fsevents.cc:6:
In file included from ../../nan/nan.h:222:
In file included from ../../nan/nan_converters.h:67:
../../nan/nan_converters_43_inl.h:22:1: warning: 'ToBoolean' is deprecated: ToBoolean can never throw.
      Use Local version. [-Wdeprecated-declarations]
X(Boolean)
^
../../nan/nan_converters_43_inl.h:18:12: note: expanded from macro 'X'
      val->To ## TYPE(isolate->GetCurrentContext())                            \
           ^
<scratch space>:143:1: note: expanded from here
ToBoolean
^
/Users/james/Library/Caches/node-gyp/12.16.1/include/node/v8.h:2663:3: note: 'ToBoolean' has been
      explicitly marked deprecated here
  V8_DEPRECATED("ToBoolean can never throw. Use Local version.",
  ^
/Users/james/Library/Caches/node-gyp/12.16.1/include/node/v8config.h:328:29: note: expanded from macro
      'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:6:
In file included from ../../nan/nan.h:222:
In file included from ../../nan/nan_converters.h:67:
../../nan/nan_converters_43_inl.h:40:1: warning: 'BooleanValue' is deprecated: BooleanValue can never
      throw. Use Isolate version. [-Wdeprecated-declarations]
X(bool, Boolean)
^
../../nan/nan_converters_43_inl.h:37:15: note: expanded from macro 'X'
  return val->NAME ## Value(isolate->GetCurrentContext());                     \
              ^
<scratch space>:150:1: note: expanded from here
BooleanValue
^
/Users/james/Library/Caches/node-gyp/12.16.1/include/node/v8.h:2701:3: note: 'BooleanValue' has been
      explicitly marked deprecated here
  V8_DEPRECATED("BooleanValue can never throw. Use Isolate version.",
  ^
/Users/james/Library/Caches/node-gyp/12.16.1/include/node/v8config.h:328:29: note: expanded from macro
      'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:6:
In file included from ../../nan/nan.h:223:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:356:37: error: too few arguments to function call, expected 2,
      have 1
  return v8::StringObject::New(value).As<v8::StringObject>();
         ~~~~~~~~~~~~~~~~~~~~~      ^
/Users/james/Library/Caches/node-gyp/12.16.1/include/node/v8.h:5531:3: note: 'New' declared here
  static Local<Value> New(Isolate* isolate, Local<String> value);
  ^
In file included from ../fsevents.cc:6:
In file included from ../../nan/nan.h:223:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:356:58: error: expected '(' for function-style cast or type
      construction
  return v8::StringObject::New(value).As<v8::StringObject>();
                                         ~~~~~~~~~~~~~~~~^
../../nan/nan_implementation_12_inl.h:356:60: error: expected expression
  return v8::StringObject::New(value).As<v8::StringObject>();
                                                           ^
In file included from ../fsevents.cc:6:
In file included from ../../nan/nan.h:2722:
../../nan/nan_object_wrap.h:24:25: error: no member named 'IsNearDeath' in 'Nan::Persistent<v8::Object,
      v8::NonCopyablePersistentTraits<v8::Object> >'
    assert(persistent().IsNearDeath());
           ~~~~~~~~~~~~ ^
/usr/include/assert.h:93:25: note: expanded from macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __FILE__, __LINE__, #e) : (void)0)
                        ^
In file included from ../fsevents.cc:6:
In file included from ../../nan/nan.h:2722:
../../nan/nan_object_wrap.h:127:26: error: no member named 'IsNearDeath' in
      'Nan::Persistent<v8::Object, v8::NonCopyablePersistentTraits<v8::Object> >'
    assert(wrap->handle_.IsNearDeath());
           ~~~~~~~~~~~~~ ^
/usr/include/assert.h:93:25: note: expanded from macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __FILE__, __LINE__, #e) : (void)0)
                        ^
../fsevents.cc:50:32: error: no template named 'Handle' in namespace 'v8'
    static void Initialize(v8::Handle<v8::Object> exports);
                           ~~~~^
../fsevents.cc:63:6: warning: field 'async_resource' will be initialized after field 'lockStarted'
      [-Wreorder]
   : async_resource("fsevents:FSEvents"), lockStarted(false) {
     ^
In file included from ../fsevents.cc:82:
../src/constants.cc:89:11: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagNone").ToLocalChecked(), Nan::New<v8...
          ^
/Users/james/Library/Caches/node-gyp/12.16.1/include/node/v8.h:3498:3: note: 'Set' has been explicitly
      marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/james/Library/Caches/node-gyp/12.16.1/include/node/v8config.h:328:29: note: expanded from macro
      'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:82:
../src/constants.cc:90:11: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagMustScanSubDirs").ToLocalChecked(), ...
          ^
/Users/james/Library/Caches/node-gyp/12.16.1/include/node/v8.h:3498:3: note: 'Set' has been explicitly
      marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/james/Library/Caches/node-gyp/12.16.1/include/node/v8config.h:328:29: note: expanded from macro
      'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:82:
../src/constants.cc:91:11: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagUserDropped").ToLocalChecked(), Nan:...
          ^
/Users/james/Library/Caches/node-gyp/12.16.1/include/node/v8.h:3498:3: note: 'Set' has been explicitly
      marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/james/Library/Caches/node-gyp/12.16.1/include/node/v8config.h:328:29: note: expanded from macro
      'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:82:
../src/constants.cc:92:11: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagKernelDropped").ToLocalChecked(), Na...
          ^
/Users/james/Library/Caches/node-gyp/12.16.1/include/node/v8.h:3498:3: note: 'Set' has been explicitly
      marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/james/Library/Caches/node-gyp/12.16.1/include/node/v8config.h:328:29: note: expanded from macro
      'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:82:
../src/constants.cc:93:11: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagEventIdsWrapped").ToLocalChecked(), ...
          ^
/Users/james/Library/Caches/node-gyp/12.16.1/include/node/v8.h:3498:3: note: 'Set' has been explicitly
      marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/james/Library/Caches/node-gyp/12.16.1/include/node/v8config.h:328:29: note: expanded from macro
      'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:82:
../src/constants.cc:94:11: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagHistoryDone").ToLocalChecked(), Nan:...
          ^
/Users/james/Library/Caches/node-gyp/12.16.1/include/node/v8.h:3498:3: note: 'Set' has been explicitly
      marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/james/Library/Caches/node-gyp/12.16.1/include/node/v8config.h:328:29: note: expanded from macro
      'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:82:
../src/constants.cc:95:11: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagRootChanged").ToLocalChecked(), Nan:...
          ^
/Users/james/Library/Caches/node-gyp/12.16.1/include/node/v8.h:3498:3: note: 'Set' has been explicitly
      marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/james/Library/Caches/node-gyp/12.16.1/include/node/v8config.h:328:29: note: expanded from macro
      'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:82:
../src/constants.cc:96:11: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagMount").ToLocalChecked(), Nan::New<v...
          ^
/Users/james/Library/Caches/node-gyp/12.16.1/include/node/v8.h:3498:3: note: 'Set' has been explicitly
      marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/james/Library/Caches/node-gyp/12.16.1/include/node/v8config.h:328:29: note: expanded from macro
      'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:82:
../src/constants.cc:97:11: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagUnmount").ToLocalChecked(), Nan::New...
          ^
/Users/james/Library/Caches/node-gyp/12.16.1/include/node/v8.h:3498:3: note: 'Set' has been explicitly
      marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/james/Library/Caches/node-gyp/12.16.1/include/node/v8config.h:328:29: note: expanded from macro
      'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:82:
../src/constants.cc:98:11: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagItemCreated").ToLocalChecked(), Nan:...
          ^
/Users/james/Library/Caches/node-gyp/12.16.1/include/node/v8.h:3498:3: note: 'Set' has been explicitly
      marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/james/Library/Caches/node-gyp/12.16.1/include/node/v8config.h:328:29: note: expanded from macro
      'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:82:
../src/constants.cc:99:11: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagItemRemoved").ToLocalChecked(), Nan:...
          ^
/Users/james/Library/Caches/node-gyp/12.16.1/include/node/v8.h:3498:3: note: 'Set' has been explicitly
      marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/james/Library/Caches/node-gyp/12.16.1/include/node/v8config.h:328:29: note: expanded from macro
      'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:82:
../src/constants.cc:100:11: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagItemInodeMetaMod").ToLocalChecked()...
          ^
/Users/james/Library/Caches/node-gyp/12.16.1/include/node/v8.h:3498:3: note: 'Set' has been explicitly
      marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/james/Library/Caches/node-gyp/12.16.1/include/node/v8config.h:328:29: note: expanded from macro
      'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:82:
../src/constants.cc:101:11: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagItemRenamed").ToLocalChecked(), Nan:...
          ^
/Users/james/Library/Caches/node-gyp/12.16.1/include/node/v8.h:3498:3: note: 'Set' has been explicitly
      marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/james/Library/Caches/node-gyp/12.16.1/include/node/v8config.h:328:29: note: expanded from macro
      'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:82:
../src/constants.cc:102:11: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagItemModified").ToLocalChecked(), Nan...
          ^
/Users/james/Library/Caches/node-gyp/12.16.1/include/node/v8.h:3498:3: note: 'Set' has been explicitly
      marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/james/Library/Caches/node-gyp/12.16.1/include/node/v8config.h:328:29: note: expanded from macro
      'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:82:
../src/constants.cc:103:11: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagItemFinderInfoMod").ToLocalChecked()...
          ^
/Users/james/Library/Caches/node-gyp/12.16.1/include/node/v8.h:3498:3: note: 'Set' has been explicitly
      marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/james/Library/Caches/node-gyp/12.16.1/include/node/v8config.h:328:29: note: expanded from macro
      'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:82:
../src/constants.cc:104:11: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagItemChangeOwner").ToLocalChecked(), ...
          ^
/Users/james/Library/Caches/node-gyp/12.16.1/include/node/v8.h:3498:3: note: 'Set' has been explicitly
      marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/james/Library/Caches/node-gyp/12.16.1/include/node/v8config.h:328:29: note: expanded from macro
      'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:82:
../src/constants.cc:105:11: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagItemXattrMod").ToLocalChecked(), Nan...
          ^
/Users/james/Library/Caches/node-gyp/12.16.1/include/node/v8.h:3498:3: note: 'Set' has been explicitly
      marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/james/Library/Caches/node-gyp/12.16.1/include/node/v8config.h:328:29: note: expanded from macro
      'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:82:
../src/constants.cc:106:11: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagItemIsFile").ToLocalChecked(), Nan::...
          ^
/Users/james/Library/Caches/node-gyp/12.16.1/include/node/v8.h:3498:3: note: 'Set' has been explicitly
      marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/james/Library/Caches/node-gyp/12.16.1/include/node/v8config.h:328:29: note: expanded from macro
      'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:82:
../src/constants.cc:107:11: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagItemIsDir").ToLocalChecked(), Nan::N...
          ^
/Users/james/Library/Caches/node-gyp/12.16.1/include/node/v8.h:3498:3: note: 'Set' has been explicitly
      marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/james/Library/Caches/node-gyp/12.16.1/include/node/v8config.h:328:29: note: expanded from macro
      'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:82:
../src/constants.cc:108:11: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagItemIsSymlink").ToLocalChecked(), Na...
          ^
/Users/james/Library/Caches/node-gyp/12.16.1/include/node/v8.h:3498:3: note: 'Set' has been explicitly
      marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/james/Library/Caches/node-gyp/12.16.1/include/node/v8config.h:328:29: note: expanded from macro
      'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../fsevents.cc:85:16: error: variable has incomplete type 'void'
void FSEvents::Initialize(v8::Handle<v8::Object> exports) {
               ^
../fsevents.cc:85:31: error: no member named 'Handle' in namespace 'v8'
void FSEvents::Initialize(v8::Handle<v8::Object> exports) {
                          ~~~~^
../fsevents.cc:85:48: error: expected '(' for function-style cast or type construction
void FSEvents::Initialize(v8::Handle<v8::Object> exports) {
                                     ~~~~~~~~~~^
../fsevents.cc:85:50: error: use of undeclared identifier 'exports'
void FSEvents::Initialize(v8::Handle<v8::Object> exports) {
                                                 ^
../fsevents.cc:85:58: error: expected ';' after top level declarator
void FSEvents::Initialize(v8::Handle<v8::Object> exports) {
                                                         ^
                                                         ;
23 warnings and 11 errors generated.
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/james/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/Users/james/.nvm/versions/node/v12.16.1/bin/node" "/Users/james/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/james/xdev/minimal-node-application/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/james/xdev/minimal-node-application/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64" "--napi_version=5" "--node_abi_napi=napi"
gyp ERR! cwd /Users/james/xdev/minimal-node-application/node_modules/fsevents
gyp ERR! node -v v12.16.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/Users/james/.nvm/versions/node/v12.16.1/bin/node /Users/james/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/james/xdev/minimal-node-application/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node --module_name=fse --module_path=/Users/james/xdev/minimal-node-application/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64 --napi_version=5 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/james/xdev/minimal-node-application/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Darwin 17.7.0
node-pre-gyp ERR! command "/Users/james/.nvm/versions/node/v12.16.1/bin/node" "/Users/james/xdev/minimal-node-application/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/james/xdev/minimal-node-application/node_modules/fsevents
node-pre-gyp ERR! node -v v12.16.1
node-pre-gyp ERR! node-pre-gyp -v v0.10.0
node-pre-gyp ERR! not ok
Failed to execute '/Users/james/.nvm/versions/node/v12.16.1/bin/node /Users/james/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/james/xdev/minimal-node-application/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node --module_name=fse --module_path=/Users/james/xdev/minimal-node-application/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64 --napi_version=5 --node_abi_napi=napi' (1)

> nodemon@1.18.9 postinstall /Users/james/xdev/minimal-node-application/node_modules/nodemon
> node bin/postinstall || exit 0

npm WARN node-babel-server@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

added 348 packages from 158 contributors and audited 3616 packages in 18.681s
found 300 vulnerabilities (104 low, 196 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```

note however that running `rm -rf node_modules && yarn install` seems to work fine

**Comment by rwieruch** [comment]
Interesting. Thanks for reporting! I fixed it by removing the `package-lock.json` and npm installing everything again. Everything should work fine with this commit https://github.com/rwieruch/minimal-node-application/commit/dd812bd305d0ad44a72951107eaa89fd2577dcb1 now. Thanks agin!
